### ISSUE TITLE
Quick Guide section shown truncated (hidden)

### ISSUE THREAD

**Issue by upekshapriya** [philgyford/daily-paper#32]
In eg https://www.theguardian.com/environment/2018/mar/27/bottle-and-can-deposit-return-scheme-gets-green-light-in-england there's a Quick Guide section with expandable text. 

<img width="755" alt="screen shot 2018-03-28 at 03 08 43" src="https://user-images.githubusercontent.com/438647/38004745-9b0d11d6-3235-11e8-991e-fd5b9d7c52b9.png">

The section starts with 'Why is plastic being demonised?' but doesn't show the 'Quick Guide' or the title so is slightly confusing and misleading, but the main problem is that the text is truncated (actually hidden).

<img width="761" alt="screen shot 2018-03-28 at 03 02 34" src="https://user-images.githubusercontent.com/438647/38004634-0ec21d02-3235-11e8-815d-e1693cd2b1ed.png">

<img width="716" alt="screen shot 2018-03-28 at 03 11 38" src="https://user-images.githubusercontent.com/438647/38004806-cc6c4d50-3235-11e8-9409-02c10c54e859.png">

Maybe the section should be removed altogether unless it is easy to reproduce the expanding box, or delineate it with a box?

**Comment by upekshapriya** [comment]
It would appear that in reader.css `.page .element-atom` is `/* Assuming 16:9 aspect ratio: */`, which seems to be the problem with the truncation. Maybe the same element is used for video containers?

If the padding-bottom is changed to 100% all the text is visible - even if there is some confusion by lack of headings or boxing.

```
.page .element-atom {
    position: relative;
    display: block;
    height: 0;
    padding: 0;
    overflow: hidden;
    padding-bottom: 100%;
}
```
This doesn't appear to affect YouTube videos which have an css class of `.element-video`

**Comment by upekshapriya** [comment]
That's perfect. Thanks! 😊

**Comment by philgyford** [comment]
Thanks for pointing it out. It should work for the various different kinds of things they shove in the middle of articles... The titles of the blocks seem to be added using JavaScript on the Guardian's site, so they're missing from the HTML we use.

It's tempting to just hide them all... let me know how you find it!

**Comment by upekshapriya** [comment]
It's clear to me as I now know the context of the boxes that it's extra information of some sort, so it's fine. 

I just found the block titles in the HTML of the page on theguardian.com so maybe it's a bug in the API if you're not getting it?

eg in https://www.theguardian.com/society/2018/mar/27/theresa-may-pledges-to-accelerate-nhs-long-term-funding-plan

```
<figure class="element element-atom" data-atom-id="28abce6b-7bb6-4f7e-981d-ca78dd416b9d" data-atom-type="qanda">
<details data-snippet-id="28abce6b-7bb6-4f7e-981d-ca78dd416b9d" data-snippet-type="qanda" class="atom atom--snippet atom--snippet--qanda">
<summary class="atom--snippet__header"> <span class="atom--snippet__label">Q&amp;A</span> <h4 class="atom--snippet__headline">What are the financial pressures on the NHS that have built up over the last decade?</h4> <button class="atom__button atom__button--large atom__button--rounded atom--snippet__handle" aria-hidden="true"> <span class="is-on">
<svg class="icon icon--plus " width="18px" height="18px" viewbox="0 0 18 18">
<path d="M8.2 0h1.6l.4 7.8 7.8.4v1.6l-7.8.4-.4 7.8H8.2l-.4-7.8L0 9.8V8.2l7.8-.4.4-7.8z"/>
</svg> Show</span> <span class="is-off">
<svg class="icon icon--minus " width="32px" height="32px" viewbox="0 0 32 32">
<rect x="5" y="15" width="22" height="3"></rect>
</svg> Hide</span> </button> </summary>
<div class="atom--snippet__body">
<p>Between 2010-11 and 2016-17, health spending increased by an average of 1.2% above inflation and increases are due to continue in real terms at a similar rate until the end of this parliament. This is far below the annual inflation-proof growth rate that the NHS enjoyed before 2010 of almost 4% stretching back to the 1950s. As budgets tighten, NHS organisations have been struggling to live within their means. In the financial year 2015-16, acute trusts recorded a deficit of £2.6bn. This was reduced to £800m last year, though only after a £1.8bn bung from the Department of <a href="https://www.theguardian.com/society/health" data-link-name="auto-linked-tag" data-component="auto-linked-tag" class="u-underline">Health</a>, which shows the deficit remained the same year on year.</p>
<p><a href="https://www.theguardian.com/society/2018/jan/04/nhs-qa-why-is-nhs-under-most-intense-pressure-in-decades" data-link-name="in body link" class="u-underline">Read a full Q&amp;A on the NHS winter crisis</a></p>
</div>
<footer class="atom--snippet__footer">
<div class="atom--snippet__feedback">
<div>
Was this helpful?
</div>
<button class="atom__button atom__button--round" value="like" aria-label="Yes">
<svg class="icon icon--thumb " width="40px" height="40px" viewbox="0 0 40 40">
<path fill="#FFF" d="M33.78 22.437l-4.228 13.98L27.93 37.5 5.062 34.14V15.503l7.8-1.517L24.354 2.5h1.624L28.9 5.426l-4.548 8.67h.107l10.477 1.31"></path>
</svg></button>
<button class="atom__button atom__button--round" value="dislike" aria-label="No">
<svg class="icon icon--thumb " width="40px" height="40px" viewbox="0 0 40 40">
<path fill="#FFF" d="M33.78 22.437l-4.228 13.98L27.93 37.5 5.062 34.14V15.503l7.8-1.517L24.354 2.5h1.624L28.9 5.426l-4.548 8.67h.107l10.477 1.31"></path>
</svg></button>
</div>
<div class="atom--snippet__ack" hidden aria-role="alert" aria-live="polite">
Thank you for your feedback.
</div>
</footer>
</details>
</figure>
```

**Comment by philgyford** [comment]
No, that doesn't come through in the API, e.g.:

```
<figure class="element element-atom"> <gu-atom data-atom-id="28abce6b-7bb6-4f7e-981d-ca78dd416b9d" data-atom-type="qanda"> <div> <div class="atom-Qanda"> <p></p> <p>Between 2010-11 and 2016-17, health spending increased by an average of 1.2% above inflation and increases are due to continue in real terms at a similar rate until the end of this parliament. This is far below the annual inflation-proof growth rate that the NHS enjoyed before 2010 of almost 4% stretching back to the 1950s. As budgets tighten, NHS organisations have been struggling to live within their means. In the financial year 2015-16, acute trusts recorded a deficit of £2.6bn. This was reduced to £800m last year, though only after a £1.8bn bung from the Department of Health, which shows the deficit remained the same year on year.</p> <p><a href="https://www.theguardian.com/society/2018/jan/04/nhs-qa-why-is-nhs-under-most-intense-pressure-in-decades">Read a full Q&amp;A on the NHS winter crisis</a></p> <p></p> </div> </div> </gu-atom> </figure>
```

From http://content.guardianapis.com/society/2018/mar/27/theresa-may-pledges-to-accelerate-nhs-long-term-funding-plan?show-elements=all&show-fields=all&api-key=test

**Comment by upekshapriya** [comment]
Let's hope they fix it! 😊

**Comment by upekshapriya** [comment]
There appears to be a related bug in the API with the following page https://www.theguardian.com/media/2018/mar/28/julian-assange-internet-connection-ecuador-embassy-cut-off-wikileaks where an explanation box (not hidden this time) has no content in the daily-paper at all, ie not just the title is removed:

<img width="702" alt="screen shot 2018-03-29 at 01 45 15" src="https://user-images.githubusercontent.com/438647/38063957-d05fb118-32f3-11e8-9b73-abebd79ef6a0.png">

<img width="922" alt="screen shot 2018-03-29 at 01 45 25" src="https://user-images.githubusercontent.com/438647/38063976-dde01eb8-32f3-11e8-8fee-950533199859.png">

**Comment by philgyford** [comment]
Odd - that box is filled in entirely by JavaScript on the live site. I've posted on the API mailing list - I've no idea if it gets read, but we'll see: https://groups.google.com/forum/#!topic/guardian-api-talk/97WiYx-gBFA

**Comment by upekshapriya** [comment]
Strange that you didn't see the code in the HTML - I found it at line 1193 - view-source:https://www.theguardian.com/media/2018/mar/28/julian-assange-internet-connection-ecuador-embassy-cut-off-wikileaks:

```
<figure class="element element-atom" data-atom-id="19e4c3a8-0a8d-4710-ad8e-9ee37c06c41a" data-atom-type="explainer">
<div class="atom atom--explainer">
<h4 class="atom--explainer__header"> Why can't Assange leave the Ecuadorian embassy? </h4>
<p>Assange sought asylum in the embassy in June 2012 following a series of legal challenges through British courts to a European arrest warrant issued by Sweden. He is technically free to leave but says he cannot because he is in breach of a warrant that was granted to extradite him to Sweden, and faces arrest. Assange has not at any point been charged with an offence under Swedish law but was sought for questioning over complaints of sexual assault by two women in 2010. Assange had raised concerns about Swedish demands that he be questioned in person,&nbsp;fearing extradition to the US.&nbsp;<br></p>
</div>
</figure>
```

**Comment by philgyford** [comment]
I'm not sure what you mean... as I said in the post, the HTMl is in the page (generated by JavaScript), but is empty in the HTML returned from the API.

**Comment by upekshapriya** [comment]
Sorry I was presumably confused by what you meant. I understood you to mean that Javascript was adding text to the site without reference to the HTML in the source code. When you say 

> the HTMl is in the page (generated by JavaScript)

I still wonder if that is what you mean, but I guess since you are not sure what I mean that we a probably talking at cross-purposes.

The code I found above was in the source sent to the browser before the Javascript processed the page.

**Comment by philgyford** [comment]
Oh yes, my mistake sorry - I must have got confused. Odd that it's styled (given a blue background and white text) using JavaScript.
